### PR TITLE
Catch and log failures in posting to search

### PR DESCRIPTION
**Pull request by timabell**
### Context
The webjob always fails because of a gateway timeout. Make it not show spurious failure.

This is similar to how we made the ucas importer go green.

### CODE REVIEW

**Comment by timabell** [comment]
[Alerting when bulk publishing has failed](https://trello.com/c/c97yYXEq/366-alerting-when-bulk-publishing-has-failed)

**Comment by timabell** [comment]
[better logging for "bulk publish to search" webjob](https://trello.com/c/1gILFshz/505-better-logging-for-bulk-publish-to-search-webjob)

**Comment by defong** [comment]
[Resolve the failure of the ucas importer webjob as it never indicated anything but failure](https://trello.com/c/aDyRjazU/411-resolve-the-failure-of-the-ucas-importer-webjob-as-it-never-indicated-anything-but-failure)

**Comment by defong** [comment]
Carded up for proper solution in 

Resolve the failure of the ucas importer webjob as it never indicated anything but failure

**Pull request merged**
