### PR TITLE
Ignore case of email address from sign-in service

### PR DESCRIPTION
**Pull request by timabell**
### Context

Users registered with a different case of email address were not able to see their courses.

### Changes proposed in this pull request

Make comparisons case-insensitive.

### CODE REVIEW

**Comment by fofr** [comment]
Should there be a test for this?

**Comment by timabell** [comment]
@fofr  I don't have strong feelings on the matter in this case. I'd be inclined to ship the fix as is for now I think.

**Comment by defong** [comment]
I think this does warrant tests, simply it is a dead end situation for a user from step 1.

**Comment by fofr** [comment]
A test would document the behaviour we expect and prevent future regressions.

**Comment by timabell** [comment]
Okay then :-)

**Comment by timabell** [comment]
Shape of services is wrong in the PR, abandoning and starting a new one.

**Pull request closed without merging**
