### PR TITLE
Plumb contact data through

### PR DESCRIPTION
**Pull request by the-daniel-rothig**
### Context

This was a fix made in manage-courses-ui but after we had moved this to manage-courses-api, alas

### Changes proposed in this pull request

Patch in the missing changes

### CODE REVIEW

**Comment by defong** [comment]
Course mapper has moved to api land not api client

**Comment by defong** [comment]
https://github.com/DFE-Digital/manage-courses-api/pull/152/files#diff-20d8e5cb243081a18960bf4bc8c5d8b0

**Comment by defong** [comment]
https://github.com/DFE-Digital/manage-courses-api/pull/152

**Comment by the-daniel-rothig** [comment]
patching this into branch `publish-course` instead.

**Pull request closed without merging**
