### PR TITLE
Don't include email in exception

### PR DESCRIPTION
**Pull request by timabell**

### CODE REVIEW

**Comment by timabell** [comment]
[capturing email in logs (bad)](https://trello.com/c/AZpzcV9S/268-capturing-email-in-logs-bad)

**Comment by benilovj** [comment]
Is the UUID from DfE Sign-in available in this context? Because you could log that instead and we still have a way to figure out who it is if needed...

**Comment by defong** [comment]
based on 

https://github.com/DFE-Digital/manage-courses-api/blob/9f1b676443c461b51c08f3c8d309ab153936b900/src/ManageCourses.Api/Middleware/BearerTokenHandler.cs#L63

it be something like

`var subjectId = User.Claims.Single(x => x.ValueType == ClaimTypes.NameIdentifier);`

**Comment by timabell** [comment]
I think we should punt that into the backlog for a broader fix https://trello.com/c/9PK6MBvd/276-add-sign-in-subject-id-to-app-insights-info

**Pull request merged**
